name: Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }} # ← твой PAT

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Set git user
        run: |
          git config user.name "igorao79"
          git config user.email "154910823+igorao79@users.noreply.github.com"

      - name: Push new version and tags
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git tag v$VERSION || true
          git push origin HEAD:main --tags
